# Generated by Django 3.2 on 2022-07-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_shipping_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
